const ruqayyaNeedsData = [
  { title: "غسول وجه", category: "عناية بالبشرة والجسم" },
  { title: "مقشر وجه", category: "عناية بالبشرة والجسم" },
  { title: "ماسك الانف", category: "عناية بالبشرة والجسم" },
  { title: "واقي تحت العين", category: "عناية بالبشرة والجسم" },
  { title: "ماسك الفم", category: "عناية بالبشرة والجسم" },
  { title: "مرطب شفة", category: "عناية بالبشرة والجسم" },
  { title: "مرطب اقدام", category: "عناية بالبشرة والجسم" },
  { title: "واقي شمس", category: "عناية بالبشرة والجسم" },
  { title: "ماسكات", category: "عناية بالبشرة والجسم" },
  { title: "علاج للتشققات", category: "صحة وطب" },
  { title: "تحاليل عامة", category: "صحة وطب" },
  { title: "سونار", category: "صحة وطب" },
  { title: "فحص الجسم", category: "صحة وطب" },
  { title: "تقويم اسنان", category: "صحة وطب" },
  { title: "فيتامينات", category: "صحة وطب" },
  { title: "دكتورة جلدية", category: "صحة وطب" },
  { title: "تراكسود رياضي أسود + نيلي", category: "ملابس" },
  { title: "ملابس بيت", category: "ملابس" },
  { title: "هاينك اسود", category: "ملابس" },
  { title: "هاينك ابيض", category: "ملابس" },
  { title: "بنطلونات اسود + رصاصي + نيلي + ابيض", category: "ملابس" },
  { title: "قمصان (3) بالوان مختلفة وحلوة", category: "ملابس" },
  { title: "ملابس داخلية بالوان مختلفة", category: "ملابس" },
  { title: "كب لون اسود نوعية زينة + ابيض", category: "ملابس" },
  { title: "شال مطاطي الينزله على الراس لون ابيض + الأسود سادة", category: "ملابس" },
  { title: "شال جريرت اسود + ابيض + الوان مختلفة", category: "ملابس" },
  { title: "كاسكيتة سودة وسادة", category: "ملابس" },
  { title: "دبابيس ابو راسين", category: "عائلة" },
  { title: "دبابيس ناعمة ام الراس", category: "عائلة" },
  { title: "دبابيس كبار ام الراس", category: "عائلة" },
  { title: "ماشات سوداء للشعر", category: "عائلة" },
  { title: "كماشات شعر", category: "عائلة" },
  { title: "قراصات شعر", category: "عائلة" },
  { title: "اساور", category: "عائلة" },
  { title: "قلائد", category: "عائلة" },
  { title: "اظافر", category: "مكياج" },
  { title: "عطور", category: "مكياج" },
  { title: "معطر جسم", category: "عناية بالبشرة والجسم" },
  { title: "جواريب", category: "ملابس" },
  { title: "احذية", category: "ملابس" },
  { title: "شنط مال طلعة", category: "عائلة" },
  { title: "دفتر مذكرات", category: "احتياجات مدرسية" },
  { title: "دفتر ورقة اسود", category: "احتياجات مدرسية" },
  { title: "قلم ابيض", category: "احتياجات مدرسية" }
];
console.log(JSON.stringify(ruqayyaNeedsData));
